#!/usr/bin/env python3
"""Generate the procedural assets used by example_gear_crusher.py.

The volumetric character is an original armadillo-like proxy built from an
implicit union and voxel tetrahedralization. No third-party geometry is used.
"""
from __future__ import annotations

import math
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent
ASSET_DIR = ROOT / "assets"
ASSET_DIR.mkdir(parents=True, exist_ok=True)


def _write_obj(path: Path, vertices: np.ndarray, triangles: np.ndarray, object_name: str) -> None:
    with path.open("w", encoding="utf-8") as f:
        f.write(f"# Generated by {Path(__file__).name}\n")
        f.write(f"o {object_name}\n")
        for x, y, z in vertices:
            f.write(f"v {x:.9g} {y:.9g} {z:.9g}\n")
        for a, b, c in triangles:
            f.write(f"f {int(a)+1} {int(b)+1} {int(c)+1}\n")


def create_spur_gear(
    teeth: int = 16,
    root_radius: float = 0.58,
    tip_radius: float = 0.78,
    half_width: float = 0.34,
    samples_per_tooth: int = 4,
) -> tuple[np.ndarray, np.ndarray]:
    """Create a closed extruded gear mesh with its shaft along +Y."""
    if samples_per_tooth != 4:
        raise ValueError("This generator currently expects four profile samples per tooth")

    profile_count = teeth * samples_per_tooth
    angles = np.arange(profile_count, dtype=np.float64) * (2.0 * math.pi / profile_count)
    # root -> tip -> tip -> root gives broad, robust teeth for collision.
    radii_pattern = np.array([root_radius, tip_radius, tip_radius, root_radius], dtype=np.float64)
    radii = np.tile(radii_pattern, teeth)
    x = radii * np.cos(angles)
    z = radii * np.sin(angles)

    front = np.stack((x, np.full_like(x, half_width), z), axis=1)
    back = np.stack((x, np.full_like(x, -half_width), z), axis=1)
    vertices = np.vstack((front, back)).astype(np.float32)

    triangles: list[tuple[int, int, int]] = []
    n = profile_count
    # Convex fan caps. The radial profile is star-shaped, so a center fan is valid.
    front_center = len(vertices)
    back_center = front_center + 1
    vertices = np.vstack(
        (
            vertices,
            np.array([[0.0, half_width, 0.0], [0.0, -half_width, 0.0]], dtype=np.float32),
        )
    )
    for i in range(n):
        j = (i + 1) % n
        triangles.append((front_center, i, j))
        triangles.append((back_center, n + j, n + i))
        # Side quad, outward winding.
        triangles.append((i, n + i, n + j))
        triangles.append((i, n + j, j))

    return vertices, np.asarray(triangles, dtype=np.int32)


def _inside_ellipsoid(points: np.ndarray, center, radii) -> np.ndarray:
    center = np.asarray(center, dtype=np.float64)
    radii = np.asarray(radii, dtype=np.float64)
    q = (points - center) / radii
    return np.einsum("ij,ij->i", q, q) <= 1.0


def _inside_capsule(points: np.ndarray, a, b, radius: float) -> np.ndarray:
    a = np.asarray(a, dtype=np.float64)
    b = np.asarray(b, dtype=np.float64)
    ab = b - a
    denom = float(np.dot(ab, ab))
    t = np.clip(((points - a) @ ab) / denom, 0.0, 1.0)
    closest = a + t[:, None] * ab
    d2 = np.einsum("ij,ij->i", points - closest, points - closest)
    return d2 <= radius * radius


def _armadillo_proxy_inside(points: np.ndarray) -> np.ndarray:
    inside = np.zeros(len(points), dtype=bool)
    ellipsoids = [
        # torso and hips
        ((0.0, 0.0, 0.12), (0.50, 0.28, 0.72)),
        ((0.0, 0.0, -0.38), (0.45, 0.29, 0.48)),
        # head and muzzle
        ((0.0, 0.0, 0.92), (0.29, 0.245, 0.34)),
        ((0.0, -0.13, 0.87), (0.22, 0.20, 0.20)),
        # ears
        ((-0.14, 0.0, 1.24), (0.105, 0.13, 0.23)),
        ((0.14, 0.0, 1.24), (0.105, 0.13, 0.23)),
        # ear/head bridges keep the voxel boundary manifold
        ((-0.13, -0.01, 1.12), (0.15, 0.18, 0.19)),
        ((0.13, -0.01, 1.12), (0.15, 0.18, 0.19)),
        # hands
        ((-0.73, 0.0, 0.02), (0.19, 0.19, 0.19)),
        ((0.73, 0.0, 0.02), (0.19, 0.19, 0.19)),
        # feet
        ((-0.34, -0.02, -1.08), (0.25, 0.24, 0.15)),
        ((0.34, -0.02, -1.08), (0.25, 0.24, 0.15)),
    ]
    for center, radii in ellipsoids:
        inside |= _inside_ellipsoid(points, center, radii)

    capsules = [
        # arms
        ((-0.34, 0.0, 0.48), (-0.67, 0.0, 0.08), 0.17),
        ((0.34, 0.0, 0.48), (0.67, 0.0, 0.08), 0.17),
        # legs
        ((-0.20, 0.0, -0.55), (-0.32, 0.0, -1.03), 0.18),
        ((0.20, 0.0, -0.55), (0.32, 0.0, -1.03), 0.18),
    ]
    for a, b, radius in capsules:
        inside |= _inside_capsule(points, a, b, radius)
    return inside


def _orient_tets_positive(vertices: np.ndarray, tets: np.ndarray) -> np.ndarray:
    p0 = vertices[tets[:, 0]]
    p1 = vertices[tets[:, 1]]
    p2 = vertices[tets[:, 2]]
    p3 = vertices[tets[:, 3]]
    det = np.einsum("ij,ij->i", np.cross(p1 - p0, p2 - p0), p3 - p0)
    neg = det < 0.0
    if np.any(neg):
        tmp = tets[neg, 0].copy()
        tets[neg, 0] = tets[neg, 1]
        tets[neg, 1] = tmp
    return tets


def tetrahedralize_implicit(spacing: float = 0.06) -> tuple[np.ndarray, np.ndarray]:
    """Voxelize the proxy and split every active cell into six conforming tets."""
    mins = np.array([-1.02, -0.42, -1.27], dtype=np.float64)
    maxs = np.array([1.02, 0.42, 1.49], dtype=np.float64)
    axes = [np.arange(lo, hi + 0.5 * spacing, spacing) for lo, hi in zip(mins, maxs)]
    nx, ny, nz = (len(a) for a in axes)

    cx = (axes[0][:-1] + axes[0][1:]) * 0.5
    cy = (axes[1][:-1] + axes[1][1:]) * 0.5
    cz = (axes[2][:-1] + axes[2][1:]) * 0.5
    centers = np.stack(np.meshgrid(cx, cy, cz, indexing="ij"), axis=-1).reshape(-1, 3)
    active = _armadillo_proxy_inside(centers).reshape(nx - 1, ny - 1, nz - 1)

    # One 6-neighbor binary closing removes rare diagonal-only voxel
    # connections that would otherwise create non-manifold boundary edges.
    def shifted(mask: np.ndarray, di: int, dj: int, dk: int) -> np.ndarray:
        out = np.zeros_like(mask)
        src = (
            slice(max(0, -di), mask.shape[0] - max(0, di)),
            slice(max(0, -dj), mask.shape[1] - max(0, dj)),
            slice(max(0, -dk), mask.shape[2] - max(0, dk)),
        )
        dst = (
            slice(max(0, di), mask.shape[0] - max(0, -di)),
            slice(max(0, dj), mask.shape[1] - max(0, -dj)),
            slice(max(0, dk), mask.shape[2] - max(0, -dk)),
        )
        out[dst] = mask[src]
        return out

    neighbors = ((1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1))
    dilated = active.copy()
    for shift in neighbors:
        dilated |= shifted(active, *shift)
    closed = dilated.copy()
    for shift in neighbors:
        closed &= shifted(dilated, *shift)
    active = closed

    # Grid index helper, x-major then y then z.
    def gid(i: int, j: int, k: int) -> int:
        return (i * ny + j) * nz + k

    # Freudenthal triangulation of a cube along 000 -> 111.
    local_tets = np.array(
        [
            [0, 1, 3, 7],
            [0, 3, 2, 7],
            [0, 2, 6, 7],
            [0, 6, 4, 7],
            [0, 4, 5, 7],
            [0, 5, 1, 7],
        ],
        dtype=np.int32,
    )
    all_tets: list[np.ndarray] = []
    used: set[int] = set()
    active_cells = np.argwhere(active)
    for i, j, k in active_cells:
        cube = np.array(
            [
                gid(i, j, k),
                gid(i + 1, j, k),
                gid(i, j + 1, k),
                gid(i + 1, j + 1, k),
                gid(i, j, k + 1),
                gid(i + 1, j, k + 1),
                gid(i, j + 1, k + 1),
                gid(i + 1, j + 1, k + 1),
            ],
            dtype=np.int32,
        )
        cell_tets = cube[local_tets]
        all_tets.append(cell_tets)
        used.update(cube.tolist())

    tets_global = np.concatenate(all_tets, axis=0)
    used_sorted = np.array(sorted(used), dtype=np.int32)
    remap = np.full(nx * ny * nz, -1, dtype=np.int32)
    remap[used_sorted] = np.arange(len(used_sorted), dtype=np.int32)

    grid = np.stack(np.meshgrid(*axes, indexing="ij"), axis=-1).reshape(-1, 3)
    vertices = grid[used_sorted].astype(np.float32)
    tets = remap[tets_global]
    tets = _orient_tets_positive(vertices, tets)
    return vertices, tets.astype(np.int32)


def boundary_triangles(tets: np.ndarray) -> np.ndarray:
    # The face order below is outward for a positively oriented tetrahedron.
    face_pattern = np.array([[1, 2, 3], [0, 3, 2], [0, 1, 3], [0, 2, 1]], dtype=np.int32)
    faces = tets[:, face_pattern].reshape(-1, 3)
    keys = np.sort(faces, axis=1)
    order = np.lexsort((keys[:, 2], keys[:, 1], keys[:, 0]))
    keys_sorted = keys[order]
    faces_sorted = faces[order]
    unique, first, counts = np.unique(keys_sorted, axis=0, return_index=True, return_counts=True)
    del unique
    return faces_sorted[first[counts == 1]].astype(np.int32)


def main() -> None:
    gear_v, gear_f = create_spur_gear()
    np.savez_compressed(ASSET_DIR / "crusher_gear.npz", vertices=gear_v, triangles=gear_f)
    _write_obj(ASSET_DIR / "crusher_gear.obj", gear_v, gear_f, "crusher_gear")

    soft_v, soft_t = tetrahedralize_implicit(spacing=0.045)
    soft_f = boundary_triangles(soft_t)
    np.savez_compressed(
        ASSET_DIR / "armadillo_proxy_tet.npz",
        vertices=soft_v,
        tets=soft_t,
        surface_triangles=soft_f,
    )
    _write_obj(ASSET_DIR / "armadillo_proxy_surface.obj", soft_v, soft_f, "armadillo_proxy")

    print(f"gear: {len(gear_v)} vertices, {len(gear_f)} triangles")
    print(f"soft proxy: {len(soft_v)} vertices, {len(soft_t)} tets, {len(soft_f)} surface triangles")


if __name__ == "__main__":
    main()
