# SPDX-FileCopyrightText: Copyright (c) 2026 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

###########################################################################
# Example Cloth Dexforce Bimanual Fold T-Shirt (two-finger gripper)
#
# Replays the same captured bimanual wrist TCP trajectory as
# ``cloth_dexforce_bimanual_fold_tshirt_v2`` but on the two-finger gripper
# URDF (``DexforceW1V021-simple``). The T-shirt mesh and solver setup are
# identical; only the gripper actuation differs (one prismatic finger per
# hand instead of the dexterous hand's many joints).
#
# Command: python -m newton.examples cloth_dexforce_bimanual_fold_tshirt_v2_simple
#
###########################################################################

from __future__ import annotations

import numpy as np
import warp as wp

import newton
import newton.examples
import newton.usd
from pxr import Usd
from newton.examples.cloth.example_cloth_dexforce_bimanual_ik_tshirt_simple import (
    SHIRT_ASSET,
    SHIRT_COLLISION_RADIUS,
    SHIRT_COLOR,
    SHIRT_DENSITY,
    SHIRT_EDGE_KD,
    SHIRT_EDGE_KE,
    SHIRT_POS,
    SHIRT_PRIM_PATH,
    SHIRT_ROT,
    SHIRT_SCALE,
    SHIRT_SELF_CONTACT_MARGIN,
    SHIRT_SELF_CONTACT_RADIUS,
    SHIRT_SOFT_CONTACT_MARGIN,
    copy_ik_to_joint_q_kernel,
    lock_joint_q_kernel,
    set_indexed_joint_q_kernel,
    Example as IKTShirtSimpleExample,
)


# Captured bimanual wrist TCP keyframes (world space). Reused verbatim from
# the dexterous-hand scene; see ``TCP_OFFSET`` in the IK scene if the
# two-finger gripper needs re-targeting.
LEFT_APPROACH_TF = wp.transform(
    wp.vec3(0.4117, 0.5145, 1.3642),
    wp.quat(0.1099, 0.6989, -0.6980, -0.1107),
)
RIGHT_APPROACH_TF = wp.transform(
    wp.vec3(0.4053, -0.5598, 1.3642),
    wp.quat(-0.0658, 0.7043, 0.7037, -0.0668),
)
LEFT_GRASP_TF = wp.transform(
    wp.vec3(0.3565, 0.1627, 1.2406),
    wp.quat(0.1103, 0.6987, -0.6982, -0.1105),
)
RIGHT_GRASP_TF = wp.transform(
    wp.vec3(0.3519, -0.1623, 1.2405),
    wp.quat(-0.0733, 0.7031, 0.7037, -0.0717),
)
LEFT_LIFT_TF = wp.transform(
    wp.vec3(0.3709, 0.1679, 1.3359),
    wp.quat(0.1105, 0.6985, -0.6981, -0.1119),
)
RIGHT_LIFT_TF = wp.transform(
    wp.vec3(0.3764, -0.1638, 1.3433),
    wp.quat(-0.0738, 0.7030, 0.7037, -0.0721),
)
LEFT_FOLD_TRAVEL_TF = wp.transform(
    wp.vec3(0.5542, 0.1679, 1.3376),
    wp.quat(0.1093, 0.6986, -0.6984, -0.1107),
)
RIGHT_FOLD_TRAVEL_TF = wp.transform(
    wp.vec3(0.6038, -0.1635, 1.3444),
    wp.quat(-0.0738, 0.7030, 0.7036, -0.0719),
)
LEFT_PLACE_TF = wp.transform(
    wp.vec3(0.6871, 0.1563, 1.2571),
    wp.quat(0.0195, 0.7068, -0.7067, -0.0247),
)
RIGHT_PLACE_TF = wp.transform(
    wp.vec3(0.6965, -0.1642, 1.2722),
    wp.quat(0.0237, 0.6998, 0.7126, -0.0439),
)
LEFT_RELEASE_TF = wp.transform(
    wp.vec3(0.6973, 0.1596, 1.4336),
    wp.quat(-0.0203, -0.7068, 0.7068, 0.0239),
)
RIGHT_RELEASE_TF = wp.transform(
    wp.vec3(0.6974, -0.1641, 1.4101),
    wp.quat(0.0238, 0.6998, 0.7126, -0.0441),
)
LEFT_SECOND_GRASP_TF = wp.transform(
    wp.vec3(0.6225, 0.2642, 1.2460),
    wp.quat(0.0216, 0.7067, -0.7067, -0.0245),
)
RIGHT_SECOND_GRASP_TF = wp.transform(
    wp.vec3(0.6223, -0.2669, 1.2432),
    wp.quat(0.0207, 0.7001, 0.7123, -0.0457),
)
LEFT_SECOND_LIFT_TF = wp.transform(
    wp.vec3(0.6428, 0.1735, 1.3145),
    wp.quat(0.0215, 0.7067, -0.7067, -0.0246),
)
RIGHT_SECOND_LIFT_TF = wp.transform(
    wp.vec3(0.6232, -0.2284, 1.3094),
    wp.quat(0.0209, 0.7001, 0.7123, -0.0461),
)
LEFT_SECOND_FOLD_TRAVEL_TF = wp.transform(
    wp.vec3(0.6436, 0.0678, 1.3139),
    wp.quat(-0.0212, -0.7067, 0.7067, 0.0250),
)
RIGHT_SECOND_FOLD_TRAVEL_TF = wp.transform(
    wp.vec3(0.6224, -0.0861, 1.3101),
    wp.quat(0.0206, 0.7001, 0.7123, -0.0457),
)
LEFT_SECOND_PLACE_TF = wp.transform(
    wp.vec3(0.6438, 0.0677, 1.2762),
    wp.quat(-0.0212, -0.7067, 0.7067, 0.0251),
)
RIGHT_SECOND_PLACE_TF = wp.transform(
    wp.vec3(0.6227, -0.0860, 1.2694),
    wp.quat(0.0207, 0.7001, 0.7123, -0.0458),
)
LEFT_SECOND_RELEASE_TF = wp.transform(
    wp.vec3(0.6438, 0.0677, 1.4336),
    wp.quat(-0.0212, -0.7067, 0.7067, 0.0251),
)
RIGHT_SECOND_RELEASE_TF = wp.transform(
    wp.vec3(0.6227, -0.0860, 1.4101),
    wp.quat(0.0207, 0.7001, 0.7123, -0.0458),
)

# First-fold right-hand keyframes captured on the two-finger gripper (world
# space). Left hand is generated by mirroring these about the Y=0 plane at
# runtime (see ``_mirror_y_transform``), so only the right side is authored.
RIGHT_FOLD_APPROACH_TF = wp.transform(
    wp.vec3(0.3811, -0.6162, 1.3640),
    wp.quat(-0.0291, 0.7067, 0.7063, -0.0304),
)
RIGHT_FOLD_GRASP_TF = wp.transform(
    wp.vec3(0.3561, -0.1282, 1.2121),
    wp.quat(-0.0834, -0.7004, -0.1058, 0.7010),
)
RIGHT_FOLD_LIFT_TF = wp.transform(
    wp.vec3(0.4263, -0.1023, 1.3009),
    wp.quat(-0.0901, -0.7051, -0.1115, 0.6945),
)
RIGHT_FOLD_PLACE_TF = wp.transform(
    wp.vec3(0.6201, -0.0666, 1.2192),
    wp.quat(0.1016, 0.8553, 0.3403, -0.3773),
)
RIGHT_FOLD_RELEASE_LIFT_TF = wp.transform(
    wp.vec3(0.6786, -0.1223, 1.3445),
    wp.quat(-0.1581, 0.9212, 0.3527, 0.0438),
)

# First-fold-only script timing (seconds). Durations for the five captured
# right-hand phases, plus a settle hold before and a post-release crack.
HOME_HOLD_TIME = 0.8
APPROACH_TIME = 2.0
GRASP_TIME = 1.4
LIFT_TIME = 1.4
FOLD_PLACE_TIME = 2.4
RELEASE_LIFT_TIME = 1.4
END_HOLD_TIME = 1.0

RELEASE_CRACK_ALPHA = 0.75
RELEASE_TIME = 1.0
RELEASE_START_TIME = (
    HOME_HOLD_TIME
    + APPROACH_TIME
    + GRASP_TIME
    + LIFT_TIME
    + FOLD_PLACE_TIME
)
RELEASE_END_TIME = RELEASE_START_TIME + RELEASE_TIME + RELEASE_LIFT_TIME
# Single fold: no second pass, so collapse the second-release windows.
SECOND_RELEASE_START_TIME = RELEASE_END_TIME
SECOND_RELEASE_END_TIME = RELEASE_END_TIME
SCRIPT_END_TIME = RELEASE_END_TIME + END_HOLD_TIME

GRASP_CLOTH_SOFT_CONTACT_MU = 1.20
GRASP_ROBOT_CLOTH_CONTACT_MU = 1.20
GRASP_TABLE_CLOTH_CONTACT_MU = 0.12
RELEASE_CLOTH_SOFT_CONTACT_MU = 0.50
RELEASE_ZERO_CLOTH_SOFT_CONTACT_MU = 0.0
RELEASE_ROBOT_CLOTH_CONTACT_MU = 0.25
RELEASE_ZERO_ROBOT_CLOTH_CONTACT_MU = 0.0
RELEASE_TABLE_CLOTH_CONTACT_MU = 0.5

TSHIRT_SIM_SUBSTEPS = 10
TSHIRT_SOLVER_ITERATIONS = 20
TSHIRT_SOFT_CONTACT_KE = 3.0e5
TSHIRT_SOFT_CONTACT_KD = 5.0e-2
TSHIRT_ROBOT_CONTACT_KE = 3.0e5
TSHIRT_TRI_KE = 1.5e3
TSHIRT_TRI_KA = 1.5e3
TSHIRT_TRI_KD = 1.0e-5
TSHIRT_EDGE_KE = 1.2
TSHIRT_EDGE_KD = 0.1

CAMERA_POS = wp.vec3(1.15, -2.10, 1.65)
CAMERA_PITCH = -16.0
CAMERA_YAW = 112.0

DEFAULT_OPEN_FINGER_GAP = 0.03


class Example(IKTShirtSimpleExample):
    def __init__(self, viewer, args):
        self.trajectory_time_scale = float(args.trajectory_time_scale)
        super().__init__(viewer, args)
        self.viewer.set_camera(CAMERA_POS, CAMERA_PITCH, CAMERA_YAW)
        # Script homes: use the captured right-hand approach pose and its Y=0
        # mirror for the left hand, so both arms start on the fold trajectory
        # rather than the IK scene's default pose.
        self.right_home_tf = RIGHT_FOLD_APPROACH_TF
        self.left_home_tf = self._mirror_y_transform(self.right_home_tf)
        self.left_tf = self.left_home_tf
        self.right_tf = self.right_home_tf
        self.motion_segments = self._build_motion_segments()

        self.sim_substeps = TSHIRT_SIM_SUBSTEPS
        self.sim_dt = self.frame_dt / self.sim_substeps
        self.solver.iterations = TSHIRT_SOLVER_ITERATIONS
        self.model.soft_contact_ke = TSHIRT_SOFT_CONTACT_KE
        self.model.soft_contact_kd = TSHIRT_SOFT_CONTACT_KD
        self._set_robot_contact_stiffness(TSHIRT_ROBOT_CONTACT_KE)
        self._set_tshirt_contact_materials(
            RELEASE_CLOTH_SOFT_CONTACT_MU,
            RELEASE_ROBOT_CLOTH_CONTACT_MU,
            RELEASE_TABLE_CLOTH_CONTACT_MU,
        )

    def _build_hand_targets(self) -> tuple[wp.array, wp.array, wp.array]:
        q_indices, open_values, grasp_values = super()._build_hand_targets()
        open_values.fill_(DEFAULT_OPEN_FINGER_GAP)
        return q_indices, open_values, grasp_values

    def _configure_particle_contacts(self) -> None:
        flags = self.model.shape_flags.numpy()
        flags |= int(newton.ShapeFlags.COLLIDE_PARTICLES)
        flags[: self.robot_shape_end] &= ~int(newton.ShapeFlags.COLLIDE_SHAPES)
        self.model.shape_flags = wp.array(flags, dtype=self.model.shape_flags.dtype, device=self.model.device)

    def _add_cloth(self, builder: newton.ModelBuilder) -> None:
        self.particle_radius = SHIRT_COLLISION_RADIUS
        self.soft_contact_margin = SHIRT_SOFT_CONTACT_MARGIN
        self.particle_self_contact_radius = SHIRT_SELF_CONTACT_RADIUS
        self.particle_self_contact_margin = SHIRT_SELF_CONTACT_MARGIN

        usd_stage = Usd.Stage.Open(newton.examples.get_asset(SHIRT_ASSET))
        usd_prim = usd_stage.GetPrimAtPath(SHIRT_PRIM_PATH)
        shirt_mesh = newton.usd.get_mesh(usd_prim)
        vertices = self._center_shirt_vertices(shirt_mesh.vertices)

        builder.add_cloth_mesh(
            vertices=[wp.vec3(float(v[0]), float(v[1]), float(v[2])) for v in vertices],
            indices=shirt_mesh.indices,
            rot=SHIRT_ROT,
            pos=SHIRT_POS,
            vel=wp.vec3(0.0, 0.0, 0.0),
            density=SHIRT_DENSITY,
            scale=1.0,
            tri_ke=TSHIRT_TRI_KE,
            tri_ka=TSHIRT_TRI_KA,
            tri_kd=TSHIRT_TRI_KD,
            edge_ke=TSHIRT_EDGE_KE,
            edge_kd=TSHIRT_EDGE_KD,
            particle_radius=self.particle_radius,
        )

    def _prepare_frame_targets(self) -> None:
        wp.copy(self.frame_joint_q_start, self.state_0.joint_q)
        script_time = (self.sim_time + self.frame_dt) * self.trajectory_time_scale

        self.left_tf, self.right_tf, grasp_alpha = self._sample_script(script_time)

        if self._is_release_no_friction_time(script_time):
            self._set_tshirt_contact_materials(
                RELEASE_ZERO_CLOTH_SOFT_CONTACT_MU,
                RELEASE_ZERO_ROBOT_CLOTH_CONTACT_MU,
                RELEASE_TABLE_CLOTH_CONTACT_MU,
            )
        elif grasp_alpha > 0.15:
            self._set_tshirt_contact_materials(
                GRASP_CLOTH_SOFT_CONTACT_MU,
                GRASP_ROBOT_CLOTH_CONTACT_MU,
                GRASP_TABLE_CLOTH_CONTACT_MU,
            )
        else:
            self._set_tshirt_contact_materials(
                RELEASE_CLOTH_SOFT_CONTACT_MU,
                RELEASE_ROBOT_CLOTH_CONTACT_MU,
                RELEASE_TABLE_CLOTH_CONTACT_MU,
            )

        self.left_pos_obj.set_target_position(0, wp.transform_get_translation(self.left_tf))
        self.left_rot_obj.set_target_rotation(0, self._quat_to_vec4(wp.transform_get_rotation(self.left_tf)))
        self.right_pos_obj.set_target_position(0, wp.transform_get_translation(self.right_tf))
        self.right_rot_obj.set_target_rotation(0, self._quat_to_vec4(wp.transform_get_rotation(self.right_tf)))
        self.ik_solver.step(self.ik_joint_q, self.ik_joint_q, iterations=self.ik_iters)
        wp.launch(
            lock_joint_q_kernel,
            dim=self.locked_q_indices.shape[0],
            inputs=[self.ik_joint_q, self.locked_q_indices, self.locked_q_values],
            device=self.model.device,
        )
        wp.launch(
            copy_ik_to_joint_q_kernel,
            dim=self.model.joint_coord_count,
            inputs=[self.ik_joint_q],
            outputs=[self.frame_joint_q_end],
            device=self.model.device,
        )
        wp.launch(
            set_indexed_joint_q_kernel,
            dim=self.hand_q_indices.shape[0],
            inputs=[self.hand_q_indices, self.hand_open, self.hand_grasp, grasp_alpha],
            outputs=[self.frame_joint_q_end],
            device=self.model.device,
        )

    @staticmethod
    def _mirror_y_transform(tf: wp.transform) -> wp.transform:
        pos = wp.transform_get_translation(tf)
        quat = wp.transform_get_rotation(tf)
        return wp.transform(
            wp.vec3(float(pos[0]), -float(pos[1]), float(pos[2])),
            wp.quat(-float(quat[0]), float(quat[1]), -float(quat[2]), float(quat[3])),
        )

    def _build_motion_segments(self) -> tuple[tuple[float, wp.transform, wp.transform, wp.transform, wp.transform, float, float], ...]:
        # Left-hand keyframes are generated by mirroring the right-hand
        # captures about the Y=0 plane (see ``_mirror_y_transform``).
        left_approach = self._mirror_y_transform(RIGHT_FOLD_APPROACH_TF)
        left_grasp = self._mirror_y_transform(RIGHT_FOLD_GRASP_TF)
        left_lift = self._mirror_y_transform(RIGHT_FOLD_LIFT_TF)
        left_place = self._mirror_y_transform(RIGHT_FOLD_PLACE_TF)
        left_release_lift = self._mirror_y_transform(RIGHT_FOLD_RELEASE_LIFT_TF)
        return (
            # 0: hold at home
            (HOME_HOLD_TIME, self.left_home_tf, self.left_home_tf, self.right_home_tf, self.right_home_tf, 0.0, 0.0),
            # 1: approach → grasp position (fingers open)
            (
                APPROACH_TIME,
                self.left_home_tf,
                left_grasp,
                self.right_home_tf,
                RIGHT_FOLD_GRASP_TF,
                0.0,
                0.0,
            ),
            # 2: close fingers (hold grasp pose, gripper closes)
            (GRASP_TIME, left_grasp, left_grasp, RIGHT_FOLD_GRASP_TF, RIGHT_FOLD_GRASP_TF, 0.0, 1.0),
            # 3: lift (fingers closed)
            (
                LIFT_TIME,
                left_grasp,
                left_lift,
                RIGHT_FOLD_GRASP_TF,
                RIGHT_FOLD_LIFT_TF,
                1.0,
                1.0,
            ),
            # 4: fold travel → place
            (
                FOLD_PLACE_TIME,
                left_lift,
                left_place,
                RIGHT_FOLD_LIFT_TF,
                RIGHT_FOLD_PLACE_TF,
                1.0,
                1.0,
            ),
            # 5: crack release (start opening gripper)
            (RELEASE_TIME, left_place, left_place, RIGHT_FOLD_PLACE_TF, RIGHT_FOLD_PLACE_TF, 1.0, RELEASE_CRACK_ALPHA),
            # 6: release lift (fully open, lift away)
            (
                RELEASE_LIFT_TIME,
                left_place,
                left_release_lift,
                RIGHT_FOLD_PLACE_TF,
                RIGHT_FOLD_RELEASE_LIFT_TF,
                RELEASE_CRACK_ALPHA,
                0.0,
            ),
            # 7: end hold
            (END_HOLD_TIME, left_release_lift, left_release_lift, RIGHT_FOLD_RELEASE_LIFT_TF, RIGHT_FOLD_RELEASE_LIFT_TF, 0.0, 0.0),
        )

    def _sample_script(self, query_time: float) -> tuple[wp.transform, wp.transform, float]:
        remaining = query_time
        for duration, left_start, left_end, right_start, right_end, grasp_start, grasp_end in self.motion_segments:
            if remaining <= duration:
                alpha = float(np.clip(remaining / max(duration, 1.0e-6), 0.0, 1.0))
                left_tf = self._interpolate_transform(left_start, left_end, alpha)
                right_tf = self._interpolate_transform(right_start, right_end, alpha)
                grasp_alpha = grasp_start * (1.0 - alpha) + grasp_end * alpha
                return left_tf, right_tf, grasp_alpha
            remaining -= duration

        _, _, left_end, _, right_end, _, grasp_end = self.motion_segments[-1]
        return left_end, right_end, grasp_end

    def _is_release_no_friction_time(self, script_time: float) -> bool:
        return (
            RELEASE_START_TIME <= script_time <= RELEASE_END_TIME
            or SECOND_RELEASE_START_TIME <= script_time <= SECOND_RELEASE_END_TIME
        )

    def _set_tshirt_contact_materials(self, cloth_mu: float, robot_mu: float, table_mu: float) -> None:
        self.model.soft_contact_mu = cloth_mu
        shape_mu = self.model.shape_material_mu.numpy()
        shape_mu[: self.robot_shape_end] = robot_mu
        shape_mu[self.robot_shape_end :] = table_mu
        self.model.shape_material_mu = wp.array(shape_mu, dtype=self.model.shape_material_mu.dtype, device=self.model.device)

    def _set_robot_contact_stiffness(self, robot_ke: float) -> None:
        shape_ke = self.model.shape_material_ke.numpy()
        shape_ke[: self.robot_shape_end] = robot_ke
        self.model.shape_material_ke = wp.array(shape_ke, dtype=self.model.shape_material_ke.dtype, device=self.model.device)

    def _offset_transform(self, tf: wp.transform, offset: wp.vec3) -> wp.transform:
        pos = wp.transform_get_translation(tf)
        return wp.transform(
            wp.vec3(float(pos[0]) + float(offset[0]), float(pos[1]) + float(offset[1]), float(pos[2]) + float(offset[2])),
            wp.transform_get_rotation(tf),
        )

    def _interpolate_transform(self, tf_a: wp.transform, tf_b: wp.transform, alpha: float) -> wp.transform:
        pos_a = self._vec3_to_np(wp.transform_get_translation(tf_a))
        pos_b = self._vec3_to_np(wp.transform_get_translation(tf_b))
        quat_a = self._quat_to_np(wp.transform_get_rotation(tf_a))
        quat_b = self._quat_to_np(wp.transform_get_rotation(tf_b))
        pos = pos_a * (1.0 - alpha) + pos_b * alpha
        quat = self._slerp_quat_xyzw(quat_a, quat_b, alpha)
        return wp.transform(wp.vec3(float(pos[0]), float(pos[1]), float(pos[2])), wp.quat(*quat.tolist()))

    def _slerp_quat_xyzw(self, quat_a: np.ndarray, quat_b: np.ndarray, alpha: float) -> np.ndarray:
        qa = self._normalize_quat(quat_a)
        qb = self._normalize_quat(quat_b)
        dot = float(np.dot(qa, qb))
        if dot < 0.0:
            qb = -qb
            dot = -dot
        dot = float(np.clip(dot, -1.0, 1.0))
        if dot > 0.9995:
            return self._normalize_quat(qa * (1.0 - alpha) + qb * alpha)

        theta_0 = np.arccos(dot)
        sin_theta_0 = np.sin(theta_0)
        theta = theta_0 * alpha
        scale_a = np.sin(theta_0 - theta) / sin_theta_0
        scale_b = np.sin(theta) / sin_theta_0
        return qa * scale_a + qb * scale_b

    def _normalize_quat(self, quat: np.ndarray) -> np.ndarray:
        norm = float(np.linalg.norm(quat))
        if norm == 0.0:
            return np.array([0.0, 0.0, 0.0, 1.0], dtype=np.float64)
        return quat / norm

    def render(self) -> None:
        self.viewer.begin_frame(self.sim_time)
        show_triangles = getattr(self.viewer, "show_triangles", True)
        if hasattr(self.viewer, "show_triangles"):
            self.viewer.show_triangles = False
        self.viewer.log_state(self.state_0)
        if hasattr(self.viewer, "show_triangles"):
            self.viewer.show_triangles = show_triangles
        self.viewer.log_mesh(
            "/fold_tshirt",
            self.state_0.particle_q,
            self.model.tri_indices.flatten(),
            hidden=not show_triangles,
            backface_culling=False,
            color=SHIRT_COLOR,
        )
        self.viewer.end_frame()

    def test_final(self) -> None:
        particle_q = self.state_0.particle_q.numpy()
        if not np.all(np.isfinite(particle_q)):
            raise ValueError("Cloth particle positions are not finite")

    @staticmethod
    def create_parser():
        parser = IKTShirtSimpleExample.create_parser()
        default_time_scale = 4.0
        parser.set_defaults(num_frames=int(np.ceil(SCRIPT_END_TIME * 60.0 / default_time_scale)) + 120)
        parser.add_argument(
            "--trajectory-time-scale",
            type=float,
            default=default_time_scale,
            help="Multiplier applied to captured trajectory time; values >1 replay faster.",
        )
        return parser


if __name__ == "__main__":
    parser = Example.create_parser()
    viewer, args = newton.examples.init(parser)
    newton.examples.run(Example(viewer, args), args)
